### ISSUE TITLE
Error decoding string: FormatException: Unexpected character (at character 19837)

### ISSUE THREAD

**Issue by rom1v** [FossifyOrg/Clock#104]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Clock/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Clock/issues) or [closed](https://github.com/FossifyOrg/Clock/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Clock/discussions) or [closed](https://github.com/FossifyOrg/Clock/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Clock/blob/master/CONTRIBUTING.md).

### Affected app version

0.6.0-beta1

### Affected Android/Custom ROM version

Android 14

### Affected device model

Pixel 8

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

I don't really know how to reproduce, I used it without problems, but since today, I have errors.

### Expected behavior

JSON parsing should not fail.

### Actual behavior

In `adb logcat`:
```
11-22 14:54:09.840 14401  9795 I flutter : ┌───────────────────────────────────────────────────────────────────────────────
11-22 14:54:09.840 14401  9795 I flutter : │ #0   listFromString (package:clock_app/common/utils/json_serialize.dart:55)
11-22 14:54:09.840 14401  9795 I flutter : │ #1   loadList (package:clock_app/common/utils/list_storage.dart:59)
11-22 14:54:09.840 14401  9795 I flutter : │ #2   <asynchronous suspension>
11-22 14:54:09.840 14401  9795 I flutter : │ #3   scheduleAlarm (package:clock_app/alarm/logic/schedule_alarm.dart:30)
11-22 14:54:09.840 14401  9795 I flutter : │ #4   <asynchronous suspension>
11-22 14:54:09.840 14401  9795 I flutter : │ #5   AlarmRunner.schedule (package:clock_app/alarm/types/alarm_runner.dart:20)
11-22 14:54:09.840 14401  9795 I flutter : │ #6   <asynchronous suspension>
11-22 14:54:09.840 14401  9795 I flutter : │ #7   OnceAlarmSchedule.schedule (package:clock_app/alarm/types/schedules/once_alarm_schedule.dart:34)
11-22 14:54:09.840 14401  9795 I flutter : │ #8   <asynchronous suspension>
11-22 14:54:09.840 14401  9795 I flutter : │ #9   Alarm.schedule (package:clock_app/alarm/types/alarm.dart:258)
11-22 14:54:09.840 14401  9795 I flutter : │ #10   <asynchronous suspension>
11-22 14:54:09.840 14401  9795 I flutter : │ #11   Alarm.enable (package:clock_app/alarm/types/alarm.dart:295)
11-22 14:54:09.840 14401  9795 I flutter : │ #12   <asynchronous suspension>
11-22 14:54:09.840 14401  9795 I flutter : │ #13   Alarm.setIsEnabled (package:clock_app/alarm/types/alarm.dart:212)
11-22 14:54:09.840 14401  9795 I flutter : │ #14   <asynchronous suspension>
11-22 14:54:09.840 14401  9795 I flutter : │ #15   _AlarmScreenState._handleEnableChangeAlarm (package:clock_app/alarm/screens/alarm_screen.dart:146)
11-22 14:54:09.840 14401  9795 I flutter : │ #16   <asynchronous suspension>
11-22 14:54:09.840 14401  9795 I flutter : ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
11-22 14:54:09.840 14401  9795 I flutter : │ ⛔ Error decoding string: FormatException: Unexpected character (at character 19837)
11-22 14:54:09.840 14401  9795 I flutter : │ ⛔ ...rvice] Update alarms in background service","isActive":false}]tive":false}]
11-22 14:54:09.840 14401  9795 I flutter : │ ⛔                                                                  ^
11-22 14:54:09.840 14401  9795 I flutter : │ ⛔ 
11-22 14:54:09.840 14401  9795 I flutter : └───────────────────────────────────────────────────────────────────────────────
```

### Screenshots/Screen recordings

![clock](https://github.com/user-attachments/assets/975d8847-4c33-43a6-b2a9-f4fce2d6e174)

**Comment by Aga-C** [comment]
It's not Fossify Clock.

**Comment by rom1v** [comment]
Oh, very sorry about that :/

I am testing several apps, I didn't remember I was testing another app.

I need to open bugs against FossifyClock though (when I set a timer for the next day, sometimes the next day it marks the alarm as "tomorrow" and does not ring). Will recheck later.
