### ISSUE TITLE
alarm can be skip off-days

### ISSUE THREAD

**Issue by hehedemuse** [FossifyOrg/Clock#29]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Clock/issues) or [closed](https://github.com/FossifyOrg/Clock/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Clock/discussions) or [closed](https://github.com/FossifyOrg/Clock/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Clock/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Ever been roused from a good, deep sleep on a public holiday, just because the alarm clock wasn't turned off? app knows the public holidays for your country; alarms won’t go off on these days (optional).

### Why do you want this feature?

I would like to request the ability to configure alarms on my days off to ensure they do not activate on those days. This feature would be especially beneficial for individuals who work irregular hours or have numerous appointments on various days of the week. Is this functionality feasible?

### Additional information

you can refer the AMdroid app.

**Comment by Aga-C** [comment]
We don't plan to add public holidays to the Clock app.
