### ISSUE TITLE
[Bug] Analog clock widget background not using Material You color

### ISSUE THREAD

**Issue by limbusdev** [FossifyOrg/Clock#31]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Clock/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Clock/issues) or [closed](https://github.com/FossifyOrg/Clock/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Clock/discussions) or [closed](https://github.com/FossifyOrg/Clock/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Clock/blob/master/CONTRIBUTING.md).

### Affected app version

5.11.2

### Affected Android/Custom ROM version

GrapheneOS / Android 14

### Affected device model

Pixel 6

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Add new widget on home screen
2. Choose analog clock
3. Keep default values

### Expected behavior

Clock background color uses a material you defined color.

### Actual behavior

Only clock face and hands are material you themed. The background is not.

### Screenshots/Screen recordings

<img alt="Screenshot_20240322-231041_1" src="https://github.com/FossifyOrg/Clock/assets/6540152/df31e6a6-ff07-4e3a-b809-64f70cac4216" width=600 />

**Comment by Aga-C** [comment]
Actually, widgets in all apps doesn't follow the current app theme. Please move this issue to https://github.com/FossifyOrg/General-Discussion/issues so it could be discussed in a context of the whole Fossify suite.
