### ISSUE TITLE
custom timezone, for main clock (an option to ignore what have set in OS) that user can add "±1:30", "±2:30" or etc

### ISSUE THREAD

**Issue by 0xRustlang** [FossifyOrg/Clock#36]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Clock/issues) or [closed](https://github.com/FossifyOrg/Clock/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Clock/discussions) or [closed](https://github.com/FossifyOrg/Clock/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Clock/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Please add an option to set custom timezone for main clock.

Please allow user to set custom timezone for main app (ignoring what has set in OS), please add that option for main clock that user can add "±1:30", "±2:30" or etc (both negative or positive amount)

This can be an alternative simpler way to implement what i requested in #30 

(Although that will be ideal, but i think this also is a good way to solve this issue although it's not ideal.

### Why do you want this feature?

Many countries recently has changed their DST laws and stopped using it and that has created many issues for those that has old devices.

If you add these options, they really save most of annoyances that this caused users and really help them.

Thank you

### Additional information

(I also has another request for exact same option for "world clock" part of app also but as you said that every issue should be about one request, i had created #37 for that and link it into this, if you want, i can merge them later)

**Comment by Aga-C** [comment]
The purpose of the main clock is to display the system time in a good-looking way. Adding such an option would be misleading because people would either:
- Confuse it with the world clock, and could even be surprised that alarms don't turn on at the proper hour.
- Be confused that it doesn't change their system time.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/FossifyOrg/Clock/issues/36#issuecomment-2016815697

@0xRustlang, if you're unaware, you *should* be able to manually set your timezone to an arbitrary UTC offset via where https://source.android.com/docs/core/connect/time#settings describes.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/FossifyOrg/Clock/issues/36#issuecomment-2032407007

Indeed, @0xRustlang, although (per https://stackoverflow.com/questions/7289660/how-to-get-utc-offset-in-seconds-in-android#comment33664811_7289708) AOSP supports float timezone offsets (standard per https://www.reddit.com/r/ISO8601/comments/177vsz2/comment/k4vpax2/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) there indeed doesn't appear to be a way to configure this via the GUI. I'll ask somewhere whether this is possible, and file a bug with AOSP for you, if that's fruitless.
