### ISSUE TITLE
Change Checkboxes to Toggle buttons in Alarms

### ISSUE THREAD

**Issue by inson1** [FossifyOrg/Clock#6]
**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
Checkboxes are ugly as hell. (at least for this use case)

**Describe the solution you'd like**
title

**Describe alternatives you've considered**
idk

**Comment by inson1** [comment]
From discussion #4 
naveensingh agreed

**Comment by inson1** [comment]
https://github.com/SimpleMobileTools/Simple-Clock/issues/544

**Comment by naveensingh** [comment]
Checkboxes have been replaced with switches and will be available in the initial release.
