### ISSUE TITLE
the alarm only shows a notification and doesn't ring nor vibrate when screen is on.

### ISSUE THREAD

**Issue by aless3** [FossifyOrg/Clock#66]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Clock/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Clock/issues) or [closed](https://github.com/FossifyOrg/Clock/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Clock/discussions) or [closed](https://github.com/FossifyOrg/Clock/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Clock/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Nameless-AOSP 13.0, built 20231121

### Affected device model

oneplus 8t 

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. go to the alarms tab
2. set an alarm for the current time+1min, so that will ring in a minute
3. do nothing and wait for them alarm without letting the device lock
4. the notification of the alarm comes and you can dismiss/snooze it as normal, but makes no sound and no vibration, it's just the notification 

### Expected behavior

1. go to the alarms tab
2. set an alarm for the current time+1min, so that will ring in a minute
3. do nothing and wait for them alarm without letting the device lock
4. the alarm rings as usual 

### Actual behavior

the notification of the alarm comes and you can dismiss/snooze it as normal, but makes no sound and no vibration, it's just the notification 

### Additional information

works if the screen is locked, and Google clock works correctly even if the screen is not locked

**Comment by Aga-C** [comment]
Do you mean that you don't have a sound at all when notification appears on the screen, or that sound stops when you open the notification drawer? 
I'm asking because when I have a screen turned on, I have a notification sound, but it disappears after opening the notification drawer.

**Comment by aless3** [comment]
the notification automatically, I think it's a normal notification.
the attached video shows where I am when the alarm starts and no sound nor vibration appears.

https://github.com/FossifyOrg/Clock/assets/7838139/94f73e43-2603-4dc8-b97d-f2e4081b98f3
(if not attached correctly I can re upload it in other ways, but I'm not sure what the best way would be)
