### ISSUE TITLE
Impossible to set black background

### ISSUE THREAD

**Issue by woj-tek** [FossifyOrg/Clock#76]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Clock/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Clock/issues) or [closed](https://github.com/FossifyOrg/Clock/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Clock/discussions) or [closed](https://github.com/FossifyOrg/Clock/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Clock/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 14 / OneUI 6.0

### Affected device model

Samsung Galaxy A52s 5G

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Go to settings (cog icon)
2. Choose "Change colours" and then select "Dark" theme
3. Choose "background" colour and set it to black ( `#000000` )

### Expected behavior

I should have app with black background

### Actual behavior

After confirming the colour app fallbacks to "Light / dark automatic" theme with greying background.

The steps works in Messages app just fine.

**Comment by Aga-C** [comment]
I've tested, and it actually occurs in all apps. When automatic light/dark was set, after changing to Dark and then changing background color, it always reverts to automatic.

Please raise this issue in [General Discussion](https://github.com/FossifyOrg/General-Discussion/issues/new?assignees=&labels=bug%2Cneeds+triage&projects=&template=bug_report.yml), so we can take care of it in all apps.
