### ISSUE TITLE
Announce next alarm with PUSH (with option to deactivate the alarm)

### ISSUE THREAD

**Issue by WebworkrNet** [FossifyOrg/Clock#91]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Clock/issues) or [closed](https://github.com/FossifyOrg/Clock/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Clock/discussions) or [closed](https://github.com/FossifyOrg/Clock/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Clock/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Announce a pending alarm via PUSH.

Add a button with the option to deactivate the next alarm. 
In the case of a series of alarms, this should only affect the next alarm and not the entire series. (Alternatively, you could also use 2 buttons for series (deactivate only this / entire alarm series).

This function should be able to be switched on and off via the settings. The notification should be active by default.
The settings could also be used to specify whether a notification should be silent or audible. My personal recommendation is to set the default to silent.

### Why do you want this feature?

As already mentioned at https://github.com/FossifyOrg/Clock/issues/13#issuecomment-2333265410, the Samsung Clock uses a similar feature. I find it very helpful.

**Comment by Aga-C** [comment]
It's already in the app, but not configurable. And there's a request to make it configurable: https://github.com/FossifyOrg/Clock/issues/14.

**Comment by WebworkrNet** [comment]
> It's already in the app, but not configurable. And there's a request to make it configurable: #14.

Sorry for the double post - I hadn't noticed this function before. This is probably due to the fact that this notification may only be displayed very late and shortly before the event.
I had explicitly searched for the term "PUSH" for the configuration, but Issue 14 did not appear.
