### ISSUE TITLE
Switching languages doesn't work

### ISSUE THREAD

**Issue by fincentxyz** [FossifyOrg/Clock#94]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Clock/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Clock/issues) or [closed](https://github.com/FossifyOrg/Clock/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Clock/discussions) or [closed](https://github.com/FossifyOrg/Clock/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Clock/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

GrapheneOS - Android 14

### Affected device model

Pixel 5

### How did you install the app?

Google Play Store

### Steps to reproduce the bug

1. Go to settings
2. Click on Language under General
3. Switch language

### Expected behavior

The language of the app changes

### Actual behavior

Nothing happens, it stays on English and the language doesn't change

**Comment by Aga-C** [comment]
Does it happen also in other Fossify apps?

**Comment by fincentxyz** [comment]
Doesn't happen on:
- Music
- Voice Recorder

Can't switch language on:
- File Manager
- Clock
- Notes
- Phone
- Contacts
- Messages

**Comment by Aga-C** [comment]
Please raise this issue in https://github.com/FossifyOrg/General-Discussion/issues.

**Comment by fincentxyz** [comment]
> @fincentxyz
> 
> It seems to me that the real issue is how languages are managed on Google Play. Google Play doesn't download all the languages at the time of install. When you select some specific language, Google Play Store has to download it first. Please check your notifications for something like 'Downloading language for Fossify...'
> 
> In my case, the selected language was automatically applied after Google Play finished downloading.
> 
> EDIT: Actually, it's possible to disable this behavior so we'll do that. Feel free to raise this issue for all apps in general discussion repo.

I just noticed the apps I downloaded with F-Droid (IzzyOnDroid repo) do use my system language (Dutch) and are able to switch languages. But the apps I downloaded with Aurora Store aren't able to switch languages.

So, is this an issue with using the Aurora Store? Or using Sandboxed Google Play on GrapheneOS?

**Comment by naveensingh** [comment]
It's not exactly an issue. It's how apps are distributed on Google Play. At the time of the install, only the necessary resources are downloaded according you to device's configuration to reduce the download size. Anything else is downloaded on-demand. 

> use my system language (Dutch)

Did you change your system language _after_ you installed Fossify Apps from Google Play/Aurora Store?

As I mentioned before, there is a way to disable this behavior on Google Play so that all languages are downloaded at once but at the cost of increasing initial download size.
